chore(workflow): remove pull request script and add check for package.json, comment rest

diff --git a/.github/workflows/build-and-release-design-kit-to-npm.yml b/.github/workflows/build-and-release-design-kit-to-npm.yml
--- a/.github/workflows/build-and-release-design-kit-to-npm.yml
+++ b/.github/workflows/build-and-release-design-kit-to-npm.yml
@@ -15,9 +15,7 @@ on:
         required: true
 
 permissions:
-  contents: write # to push changes to the repository
   actions: write # to create a release
-  pull-requests: write # to create pull requests
 
 jobs:
   build:
@@ -28,6 +26,15 @@ jobs:
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
 
+      - name: Check release version in package.json
+        run: |
+          if ! grep -q "  \"version\": \"${VERSION}\"" libs/design-kit/package.json; then
+            echo "Error: Release version ${{ inputs.release-version }} not found in package.json"
+            exit 1
+          fi
+        env:
+          VERSION: ${{ inputs.release-version }}
+
       - name: Check release version in CHANGELOG
         run: |
           if ! grep -q "## ${VERSION//./\\.}" libs/storybook/src/stories/main/changelog.mdx; then
@@ -37,37 +44,24 @@ jobs:
         env:
           VERSION: ${{ inputs.release-version }}
 
-      - name: Set git config
-        run: |
-          git config --global user.name "github-actions"
-          git config --global user.email "github-actions@github.com"
-
-      - name: Perform release
-        run: |
-          cd libs/design-kit
-          sed -i -E 's/"version": "[^"]+"/"version": "'"${{ inputs.release-version }}"'"/' package.json
-          git checkout -b release/design-kit-${{ inputs.release-version }}
-          git add package.json
-          git commit -m "ci(design-kit): update package.json with version ${{ inputs.release-version }}"
-
       # Install dependencies & build
-      - name: Setup node
-        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
-        with:
-          node-version-file: '.nvmrc'
+      # - name: Setup node
+      #   uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
+      #   with:
+      #     node-version-file: '.nvmrc'
 
-      - name: Cache npm dependencies
-        uses: actions/cache@387e18722e6ff315b24a3b8b071feddd27b7bf7e # v3.4.2
-        with:
-          path: ~/.npm
-          key: npm-${{ hashFiles('package-lock.json') }}
-          restore-keys: npm-
+      # - name: Cache npm dependencies
+      #   uses: actions/cache@387e18722e6ff315b24a3b8b071feddd27b7bf7e # v3.4.2
+      #   with:
+      #     path: ~/.npm
+      #     key: npm-${{ hashFiles('package-lock.json') }}
+      #     restore-keys: npm-
 
-      - name: Install dependencies
-        run: npm ci
+      # - name: Install dependencies
+      #   run: npm ci
 
-      - name: Build Design Kit
-        run: npm run build:design-kit
+      # - name: Build Design Kit
+      #   run: npm run build:design-kit
 
       # - name: Publish to NPM
       #   uses: JS-DevTools/npm-publish@19c28f1ef146469e409470805ea4279d47c3d35c # v3.1.1
@@ -76,22 +70,3 @@ jobs:
       #     token: ${{ secrets.NPM_TOKEN }}
       #     access: public
       #     dry-run: false
-
-      # Push release to main
-      - name: Push release
-        run: |
-          git push origin release/design-kit-${{ inputs.release-version }}
-
-      - name: Create Pull Request
-        uses: actions/github-script@v7
-        with:
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          script: |
-            await github.rest.pulls.create({
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              title: "Automatically update design-kit package to version ${{ inputs.release-version }}",
-              head: "release/design-kit-${{ inputs.release-version }}",
-              base: "main",
-              body: "Created by GitHub Action"
-            });
